# Generated by Django 4.1.1 on 2022-10-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('parentezco', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=3)),
                ('fecha_de_nacimiento', models.DateField()),
            ],
        ),
    ]
